### ISSUE TITLE
Personal PDS errors

### ISSUE THREAD

**Issue by Gregoor** [Gregoor/skylights#1]
https://bsky.app/profile/blockstackers.net/post/3lc3swjbx4c2n

**Comment by benvanstaveren** [comment]
Hi! That's me ;) Took a look at the code and indeed, if you use the 'bsky.social/xrpc' you're talking to Bluesky's Entryway (basically an aggregator of their many, many PDS's), but that does not include self-hosted PDS's. I think you're best off making the URL a passable parameter, you can extract the proper base URL from the DID document by iterating the service array for the entry that has "#atproto_pds" as it's id, then taking the serviceEndpoint key and appending "/xrpc" to that :D 

You would then also bypass the bsky.social completely and go straight to the PDS holding the users' data

**Comment by Gregoor** [comment]
Thank you for the extra info, that already helps my mental model. One question:

> [...] DID document by iterating the service array [...]

Which document is that, and where do I get?

**Comment by benvanstaveren** [comment]
It's the result from a lookup on plc.directory - ahh, not entirely sure where that would live in your code, but you can fetch it by loading https://plc.directory/did:plc:.... and you'll get a JSON doc returned. I think you may be using it already to map the did:plc to a handle but not entirely sure, haven't quite grasped how TS works :D

**Comment by Gregoor** [comment]
I think it works! Unfortunately oauth does not work for preview deployments, but it looks good on dev, so I think I'll merge and we'll test on prod 🧙🏼‍♂️

**Comment by Gregoor** [comment]
With personal PDS' I'm a little extra aware that I have not added caching yet, thus hammering PDS on every request. Maybe I should prioritize that and only merge once I've added that..

**Comment by benvanstaveren** [comment]
I mean, I don't mind a little hammering - I'd say test first, if that works call it good and then add the caching on top afterwards. Besides, the getRecord isn't a very expensive operation really, I think...

**Comment by MDrollette** [comment]
To throw an extra wrench in - I'm using a did:web on my self-hosted PDS 🙃 https://skylights.my/profile/matt.rows.io

So resolving the PDS URL from the did document still needs to happen, but simply fetching the DID document from plc.directory isn't enough. Using a DID resolver library that automatically handles did:web in addition to did:plc would fix that.

**Comment by benvanstaveren** [comment]
^  that - I knew I was forgetting something. There's a did resolver in Bluesky's atproto SDK I think :D

**Comment by Gregoor** [comment]
https://github.com/bluesky-social/atproto/tree/main/packages/identity
This might be it?

**Comment by Gregoor** [comment]
Great, updated the PR and I can view @MDrollette's PDS now:
https://skylights-git-ppds-gregors-projects-32c57e9d.vercel.app/profile/matt.drollette.com
Thanks for the pointers!

I'll still take a minute to reflect on whether I can add caching fast enough to not feel about leaving this hanging. Sorry for the 2nd class citizen PPDS support, I think it's great that you're self-hosting and I wanna find time to do that as well soon.

**Comment by benvanstaveren** [comment]
Hah no worries, it's just one of those things that's easy to overlook (also because the bluesky sdk docs imply heavily you always interact with bsky.social), and at least it's been identified and fixed :D 

I wouldn't sweat the caching, it's nice to add but I don't think it's a must, depends a bit on how much traffic one drives to their profile I guess; it can't be heavier than the relay scrape and that's so lightweight it doesn't even show as a blip on my traffic metrics. Also most self-hosted PDS's have a single account on them, maybe some with a few more due to test accounts and fun things like that, so the impact is low.

**Comment by Gregoor** [comment]
I see! My mental-model/fear might be off, I guess I assumed the relay cleverly only goes for change events and thus fans out small diffs that clever app views can build into up-to-date snapshots. Whereas skylights currently runs to the PDS for every single request, so if (big IF rn) your profile goes viral, skylights would drown your PDS in requests?!

**Comment by benvanstaveren** [comment]
Late to the party! But yes, if I get super viral then my PDS will probably fall over, or at the very least have an unpleasant time. But I think that would take half the network suddenly looking at my stuff...
