### ISSUE TITLE
Search by ISBN

### ISSUE THREAD

**Issue by steveklabnik** [Gregoor/skylights#3]
Hey there! I dunno if you're taking feature requests, but please consider this a "this would be a cool idea" and not some sort of demand.

I want to review a book that has a lot of various editions. Search isn't bringing up the specific one that I want. If I could search by ISBN number, that would let me instantly get the exact book I'm looking for.

Thanks for building this! It's great to see more atproto apps.

**Comment by Gregoor** [comment]
Hey Steve, thanks for the nice words, I'm absolutely taking ideas!

This one I've added this morning though, so if it doesn't work it might mean the book is not in open-library or the [ISBN detection](https://github.com/Gregoor/skylights/blob/7f65a4edfab7f6c903af4bec5f50c67e972059b2/web/app/search/client.tsx#L36-L48) is faulty. Do you have the number for me?

**Comment by steveklabnik** [comment]
Ah interesting!

`0140445684` is the isbn-10, https://openlibrary.org/books/OL3086509M/Capital is the link on openlibrary.

I wonder if it's the leading zero? Since it's being converted to a `Number`...

**Comment by Gregoor** [comment]
Oooohhh you are absolutely right, a falsehood this programmers implicitly believed about ISBNs 🙈 

fixed in [69471fb](https://github.com/Gregoor/skylights/commit/69471fb34aea42e2379dbbede7e59cc97d6b42a4)
