### ISSUE TITLE
Misinputs when clicking stars

### ISSUE THREAD

**Issue by DenowRammy** [Gregoor/skylights#7]
Running Mozilla Firefox 133.0 on Linux Mint 22

When I click a star, it can be difficult to get the input to be accepted correctly even though I'm visibly clicking what I intend to. I find it especially happens when I'm pressing the left side of the 5th star (4.5 stars) I have to click many times to get the input to register correctly.

**Comment by Gregoor** [comment]
Thanks for the report, I'm also seeing the stars being rendered too small in FF. I'll change those to SVGs and add a more accurate click handler.
